wandb_version: 1

epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.4
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688136108.840993
    t:
      1:
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.10.6
      5: 0.15.4
      8:
      - 1
      - 5
    framework: huggingface
