wandb_version: 1

epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1689311240.340016
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.11.4
      5: 0.15.5
      8:
      - 1
      - 5
