wandb_version: 1

epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.9.12
    cli_version: 0.15.4
    framework: huggingface
    huggingface_version: 4.31.0.dev0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688063484.042503
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.9.12
      5: 0.15.4
      6: 4.31.0.dev0
      8:
      - 1
      - 5
